name: Build Acesso Remoto Protork

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  windows:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: protork
      windows-only: true
    secrets: inherit
